on:
  push:
    branches:
      - "**"
  pull_request_target:
    branches:
      - main
name: Build Mobile
jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: mobile
    strategy:
      matrix:
        node-version: [14.x]
    steps:
      - uses: actions/checkout@v2
      - name: Node ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
          cache-dependency-path: '**/package-lock.json'
      - name: Install dependencies
        run: npm install expo-cli --global
      - run: yarn add expo
     # - run: npm run lint
      - run: npm run test:ci